"""
Configurazione del meteo e ambiente
"""

# --- Clima e Geografia ---
PLANET_AXIAL_TILT_DEGREES = 28.183239
PLANET_ORBITAL_ECCENTRICITY = 1 / 34.9930626953
DEFAULT_LATITUDE_ANTHALYS = 45.0
DEFAULT_ALTITUDE_ANTHALYS_METERS = 300
WEATHER_CALIBRATION_LOGFILE = "weather_calibration.log"
ENABLE_WEATHER_CALIBRATION_LOG = False