"""
Configurazione NPC, tratti, bisogni e ciclo di vita
"""

from .time_config import DXY, DXM

# --- Generazione NPC ---
MIN_TRAITS_PER_NPC = 3
MAX_TRAITS_PER_NPC = 5
MAX_NPC_ACTIVE_INTERESTS = 3

# --- Ciclo di Vita ---
LIFE_STAGE_AGE_THRESHOLDS_DAYS = {
    "INFANCY": 0,
    "TODDLERHOOD": DXY * 1,
    "EARLY_CHILDHOOD": DXY * 3,
    "MIDDLE_CHILDHOOD": DXY * 6,
    "ADOLESCENCE": DXY * 12,
    "EARLY_ADULTHOOD": DXY * 20,
    "MIDDLE_ADULTHOOD": DXY * 40,
    "LATE_ADULTHOOD": DXY * 60,
    "ELDERLY": DXY * 80
}

AGE_SENIOR_STARTS_CONSIDER_DEATH_YEARS = 75.0
AGE_SENIOR_STARTS_CONSIDER_DEATH_DAYS = round(AGE_SENIOR_STARTS_CONSIDER_DEATH_YEARS * DXY)
DAILY_DEATH_CHANCE_MULTIPLIER_SENIOR = 0.0005

# --- Riproduzione e Sessualità ---
MIN_AGE_PUBERTY_FERTILITY_YEARS = 13
MIN_AGE_PUBERTY_FERTILITY_DAYS = MIN_AGE_PUBERTY_FERTILITY_YEARS * DXY

MIN_AGE_FOR_INTIMACY_YEARS = 14
MIN_AGE_FOR_INTIMACY_DAYS = MIN_AGE_FOR_INTIMACY_YEARS * DXY
MAX_AGE_FOR_INTIMACY_YEARS = 70
MAX_AGE_FOR_INTIMACY_DAYS = MAX_AGE_FOR_INTIMACY_YEARS * DXY

PREGNANCY_CHANCE_FEMALE = 0.20
PREGNANCY_DURATION_MONTHS_GAME = 9
PREGNANCY_DURATION_DAYS_GAME = PREGNANCY_DURATION_MONTHS_GAME * DXM

MIN_AGE_START_PREGNANCY_FEMALE_YEARS = 14
MIN_AGE_START_PREGNANCY_FEMALE_DAYS = MIN_AGE_START_PREGNANCY_FEMALE_YEARS * DXY
MAX_AGE_FERTILE_FEMALE_YEARS = 48
MAX_AGE_FERTILE_FEMALE_DAYS = MAX_AGE_FERTILE_FEMALE_YEARS * DXY

AGE_START_MENSTRUAL_CYCLE_YEARS_SET = {11.0, 13.0}
AGE_START_MENSTRUAL_CYCLE_DAYS_SET = {round(year * DXY) for year in AGE_START_MENSTRUAL_CYCLE_YEARS_SET}
AGE_MENOPAUSE_YEARS_SET = {50.0, 60.0}
AGE_MENOPAUSE_DAYS_SET = {round(year * DXY) for year in AGE_MENOPAUSE_YEARS_SET}

CHANCE_NPC_IS_HETEROSEXUAL = 0.85
CHANCE_NPC_IS_HOMOSEXUAL = 0.07
CHANCE_NPC_IS_BISEXUAL = 0.05
CHANCE_NPC_IS_PANSEXUAL = 0.03
CHANCE_NPC_IS_ASEXUAL_SPECTRUM = 0.02
CHANCE_NPC_IS_AROMANTIC_SPECTRUM = 0.02
CHANCE_ROMANTIC_MATCHES_SEXUAL = 0.95

# --- Sistema dei Bisogni ---
NEED_MIN_VALUE = 0.0
NEED_MAX_VALUE = 100.0
NEED_DEFAULT_START_MIN = 50.0
NEED_DEFAULT_START_MAX = 80.0

NEED_DECAY_RATES = {
    "ACHIEVEMENT": -0.2,
    "AUTONOMY": -0.3,
    "BLADDER": -8.0,
    "COMFORT": -1.0,
    "CREATIVITY": -0.3,
    "ENERGY": -5.0,
    "ENVIRONMENT": -0.5,
    "FUN": -3.0,
    "HUNGER": -4.2,
    "HYGIENE": -2.0,
    "INTIMACY": -1.5,
    "LEARNING": -0.2,
    "SAFETY": -0.5,
    "SOCIAL": -2.5,
    "SPIRITUALITY": -0.4
}

NEED_CRITICAL_THRESHOLD = 10.0
NEED_LOW_THRESHOLD = 25.0
NEED_HIGH_THRESHOLD = 75.0