"""
Configurazione del sistema educativo
"""

from core.config.time_config import DXY

# --- Livelli Scolastici ---
SCHOOL_AGE_START_INFANCY_EDUCATION_YEARS = 1.0
SCHOOL_AGE_START_LOWER_ELEMENTARY_YEARS = 3.0
SCHOOL_AGE_START_UPPER_ELEMENTARY_YEARS = 6.0
SCHOOL_AGE_START_LOWER_MIDDLE_YEARS = 9.0
SCHOOL_AGE_START_UPPER_MIDDLE_YEARS = 12.0
SCHOOL_AGE_START_HIGH_SCHOOL_YEARS = 15.0
SCHOOL_AGE_START_PRE_UNIVERSITY_YEARS = 18.0
SCHOOL_AGE_START_UNIVERSITY_YEARS = 21.0

SCHOOL_AGE_START_INFANCY_EDUCATION_DAYS = round(SCHOOL_AGE_START_INFANCY_EDUCATION_YEARS * DXY)
SCHOOL_AGE_START_LOWER_ELEMENTARY_DAYS = round(SCHOOL_AGE_START_LOWER_ELEMENTARY_YEARS * DXY)
SCHOOL_AGE_START_UPPER_ELEMENTARY_DAYS = round(SCHOOL_AGE_START_UPPER_ELEMENTARY_YEARS * DXY)
SCHOOL_AGE_START_LOWER_MIDDLE_DAYS = round(SCHOOL_AGE_START_LOWER_MIDDLE_YEARS * DXY)
SCHOOL_AGE_START_UPPER_MIDDLE_DAYS = round(SCHOOL_AGE_START_UPPER_MIDDLE_YEARS * DXY)
SCHOOL_AGE_START_HIGH_SCHOOL_DAYS = round(SCHOOL_AGE_START_HIGH_SCHOOL_YEARS * DXY)
SCHOOL_AGE_START_PRE_UNIVERSITY_DAYS = round(SCHOOL_AGE_START_PRE_UNIVERSITY_YEARS * DXY)
SCHOOL_AGE_START_UNIVERSITY_DAYS = round(SCHOOL_AGE_START_UNIVERSITY_YEARS * DXY)

# --- Calendario Scolastico ---
SCHOOL_MONTHS_PERIOD_1_START = 1
SCHOOL_MONTHS_PERIOD_1_END = 6
SCHOOL_MONTHS_PERIOD_2_START = 10
SCHOOL_MONTHS_PERIOD_2_END = 15

# --- Orari e Attività ---
SCHOOL_HOURS_START = 8
SCHOOL_HOURS_END = 15
HOMEWORK_DURATION_TICKS = 60
HOMEWORK_HOURS_START = 16
HOMEWORK_HOURS_END = 20

# --- Prestazioni Scolastiche ---
INITIAL_SCHOOL_PERFORMANCE = 50.0
MAX_SCHOOL_PERFORMANCE = 100.0
MIN_SCHOOL_PERFORMANCE = 0.0
PERF_CHANGE_ATTEND_SCHOOL_BASE = 1.0
PERF_CHANGE_MOOD_HAPPY_BONUS = 0.5
PERF_CHANGE_MOOD_UNHAPPY_MALUS = -0.8
PERF_CHANGE_ENERGY_LOW_MALUS = -0.5
PERF_CHANGE_ENERGY_CRITICAL_MALUS = -1.0
PERF_CHANGE_HOMEWORK_DONE_BONUS = 3.0
PERF_CHANGE_HOMEWORK_MISSED_MALUS = -4.0
PERF_CHANGE_SKIPPED_SCHOOL_MALUS = -5.0
CHANCE_TO_SKIP_SCHOOL_BASE = 0.05

SCHOOL_PERF_EXCELLENT_THRESHOLD = 85
SCHOOL_PERF_POOR_THRESHOLD = 35
MOOD_BOOST_EXCELLENT_PERF = 15
MOOD_PENALTY_POOR_PERF = -15
MOODLET_DURATION_SCHOOL_PERF_DAYS = 3.0

# --- Apprendimento Abilità ---
BASE_SKILL_GAIN_PER_SCHOOL_DAY = 0.05
BASE_SKILL_GAIN_PER_HOMEWORK_DONE = 0.08
SKILL_GAIN_PERF_TIER_1_THRESHOLD = 25.0
SKILL_GAIN_PERF_TIER_2_THRESHOLD = 50.0
SKILL_GAIN_PERF_TIER_3_THRESHOLD = 75.0
LEARNING_SKILL_GAIN_MULTIPLIER_POOR = 0.2
LEARNING_SKILL_GAIN_MULTIPLIER_AVERAGE = 0.6
LEARNING_SKILL_GAIN_MULTIPLIER_GOOD = 1.0
LEARNING_SKILL_GAIN_MULTIPLIER_EXCELLENT = 1.5