"""
Configurazione delle relazioni sociali e servizi
"""

from core.config.time_config import DXY

# --- Servizi Sociali ---
AMORI_CURATI_PHASE1_ACCESS_MIN_AGE_YEARS = 18
AMORI_CURATI_PHASE1_ACCESS_MIN_AGE_DAYS = AMORI_CURATI_PHASE1_ACCESS_MIN_AGE_YEARS * DXY

AMORI_CURATI_PHASE2_ACCESS_MIN_AGE_YEARS = 25
AMORI_CURATI_PHASE2_ACCESS_MIN_AGE_DAYS = AMORI_CURATI_PHASE2_ACCESS_MIN_AGE_YEARS * DXY

FRIEND_CONNECT_MIN_ACCESS_AGE_YEARS = 14
FRIEND_CONNECT_MIN_ACCESS_AGE_DAYS = FRIEND_CONNECT_MIN_ACCESS_AGE_YEARS * DXY

MAX_MATCHMAKING_SUGGESTIONS = 3
FRIEND_MAX_AGE_DIFFERENCE_YEARS = 10

# --- Relazioni e Appuntamenti ---
DATING_CANDIDATE_MAX_AGE_DIFFERENCE_YEARS = 15 
DATING_CANDIDATE_MIN_AGE_YEARS = AMORI_CURATI_PHASE1_ACCESS_MIN_AGE_YEARS
DATING_CANDIDATE_MIN_AGE_DAYS = DATING_CANDIDATE_MIN_AGE_YEARS * DXY