"""
Configurazione dell'interfaccia utente e report
"""

# --- Interfaccia Utente ---
HEADER_HEIGHT_CURSES = 3
LOG_WINDOW_HEIGHT_CURSES = 10
MAIN_WINDOW_HEIGHT_CURSES = 20
STATUS_BAR_HEIGHT_CURSES = 1

# --- Report e Salvataggi ---
AUTOSAVE_ON_DAY_END = True
ENABLE_CONSOLE_DAILY_REPORT = True
ENABLE_CONSOLE_MONTHLY_REPORT = True
ENABLE_CONSOLE_ANNUAL_REPORT = True
ENABLE_CONSOLE_HOURLY_SUMMARY_IN_CONTINUOUS = True
HOURLY_SUMMARY_INTERVAL = 3
HOURLY_SUMMARY_INTERVAL_CONTINUOUS_MODE = 6

ENABLE_FILE_REPORTS = True
REPORT_FILENAME = "simai_simulation_chronicles.log"
ENABLE_FILE_DAILY_REPORT = True
ENABLE_FILE_MONTHLY_REPORT = True
ENABLE_FILE_ANNUAL_REPORT = True

# --- Colori ANSI ---
class ANSIColors:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    MALE_COLOR = "\033[96m"
    FEMALE_COLOR = "\033[95m"
    NEED_HUNGER_COLOR = "\033[31m"
    NEED_ENERGY_COLOR = "\033[34m"
    NEED_SOCIAL_COLOR = "\033[32m"
    NEED_FUN_COLOR = "\033[33m"
    NEED_HYGIENE_COLOR = "\033[36m"
    NEED_BLADDER_COLOR = "\033[35m"
    NEED_INTIMACY_COLOR = "\033[91m"
    EVENT_POSITIVE_COLOR = "\033[92m"
    EVENT_NEGATIVE_COLOR = "\033[91m"
    EVENT_NEUTRAL_COLOR = "\033[94m"
    REPORT_TITLE_COLOR = "\033[1m\033[93m"
    DEBUG_COLOR = "\033[1m\033[93m"