# simai/game/config.py
# MODIFIED: Added DEBUG_AI_ACTIVE, cleaned up comments.

import pygame 
import os
import datetime 

# --- Game Name and Versioning ---
GAME_NAME = "SimAI"
CORE_VERSION = "0.3.0" 
BUILD_METADATA = datetime.datetime.now().strftime("%Y%m%d%H%M%S") 
FULL_VERSION_INTERNAL = f"{CORE_VERSION}+{BUILD_METADATA}" 
WINDOW_TITLE = f"{GAME_NAME} v{CORE_VERSION}" 
# --- End Game Name and Versioning ---

# --- DEBUG Settings ---
DEBUG_MODE_ACTIVE = True       # Flag generale per attivare logiche di debug specifiche (es. randomizzazione bisogni)
DEBUG_AI_ACTIVE = True         # NUOVO: Flag per attivare stampe di debug verbose (IA, Save/Load, Utils, etc.)

# Valori specifici per DEBUG_MODE_ACTIVE = True
DEBUG_ENERGY_INITIAL_MIN_PCT = 0.05 
DEBUG_ENERGY_INITIAL_MAX_PCT = 0.15
DEBUG_HUNGER_INITIAL_MIN_PCT = 0.70 
DEBUG_HUNGER_INITIAL_MAX_PCT = 0.85 

# --- Screen and General Settings ---
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
FPS = 60
PANEL_UI_HEIGHT = 150

# --- Grid and Tiles ---
TILE_SIZE = 32
GRID_WIDTH = SCREEN_WIDTH // TILE_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // TILE_SIZE

# --- Time System ---
GAME_HOURS_IN_DAY = 28
INITIAL_START_HOUR = 7.0 
DAYS_PER_MONTH = 24    
MONTHS_PER_YEAR = 18   
GAME_DAYS_PER_YEAR = DAYS_PER_MONTH * MONTHS_PER_YEAR
TIME_SPEED_SETTINGS = { 
    0: float('inf'), 1: 240.0, 2: 120.0, 3: 60.0, 4: 30.0, 5: 15.0
}
TIME_SPEED_SLEEP_ACCELERATED_INDEX = 5 # Indice della velocità massima quando tutti dormono

# --- Colors ---
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
NEED_COLOR_VERY_BAD = (255, 0, 0)    
NEED_COLOR_BAD = (255, 120, 0)   
NEED_COLOR_MEDIUM = (255, 255, 0)  
NEED_COLOR_OKAY = (120, 255, 0)  
NEED_COLOR_GOOD = (0, 200, 0)    

TEXT_COLOR_LIGHT = (220, 220, 220)
TEXT_COLOR_DARK = (30, 30, 50)
DEBUG_GRID_COLOR = (50, 50, 50)
DEBUG_OBSTACLE_COLOR = (100, 0, 0)

NPC_ALPHA_COLOR_MALE = (100, 149, 237) 
NPC_BETA_COLOR_FEMALE = (255, 105, 180)

DEEP_NIGHT_COLOR = (10, 10, 30)
PRE_DAWN_COLOR = (25, 25, 55)
VIVID_DAWN_COLOR = (100, 90, 140)
EARLY_MORNING_COLOR = (120, 140, 190)
FULL_MORNING_COLOR = (135, 206, 235)
BRIGHT_DAY_COLOR = (170, 225, 255)
WARM_AFTERNOON_COLOR = (220, 200, 160)
EARLY_SUNSET_COLOR = (255, 180, 100)
VIVID_SUNSET_COLOR = (255, 130, 70)
RED_SUNSET_COLOR = (200, 80, 60)
TWILIGHT_COLOR = (70, 60, 90)

SKY_KEYFRAMES = [ 
    (0, DEEP_NIGHT_COLOR), (4, PRE_DAWN_COLOR), (6, VIVID_DAWN_COLOR),
    (8, EARLY_MORNING_COLOR), (11, FULL_MORNING_COLOR), (14, BRIGHT_DAY_COLOR),
    (17, WARM_AFTERNOON_COLOR), (19, EARLY_SUNSET_COLOR), (21, VIVID_SUNSET_COLOR),
    (23, RED_SUNSET_COLOR), (25, TWILIGHT_COLOR), (28, DEEP_NIGHT_COLOR) 
]

# --- Asset Paths ---
GAME_DIR_PATH = os.path.dirname(os.path.abspath(__file__))
BASE_ASSET_PATH = os.path.join(GAME_DIR_PATH, "assets") 
IMAGE_PATH = os.path.join(BASE_ASSET_PATH, "images")
ICON_PATH = os.path.join(IMAGE_PATH, "icons") 
FURNITURE_IMAGE_PATH = os.path.join(IMAGE_PATH, "furnitures") 
CHARACTER_SPRITE_PATH = os.path.join(IMAGE_PATH, "characters")

# --- Interactive Objects: Base Properties ---
BED_SPRITESHEET_BASE_RECT_COORDS = (0, 0, 64, 81)  
BED_SPRITESHEET_COVER_RECT_COORDS = (0, 106, 64, 22) 
DESIRED_BED_WIDTH = 64 # Larghezza effettiva dell'oggetto letto nel mondo
DESIRED_BED_HEIGHT = 81 # Altezza effettiva della base del letto (senza coperta separata)
BED_COLOR_FALLBACK = (100,70,30) 
DESIRED_BED_X = SCREEN_WIDTH - DESIRED_BED_WIDTH - 10 
DESIRED_BED_Y = SCREEN_HEIGHT - PANEL_UI_HEIGHT - DESIRED_BED_HEIGHT - 10 # Posiziona la base
BED_COVER_DRAW_OFFSET_Y = 26 # Offset Y dal DESIRED_BED_Y per disegnare la coperta
BED_SLOT_1_OFFSET = (TILE_SIZE // 2, TILE_SIZE * 1.5) # (dx, dy) dallo spigolo del bed_rect
BED_SLOT_2_OFFSET = (TILE_SIZE * 1.5, TILE_SIZE * 1.5) # Esempio per un letto di 2xN tiles
# Offset per i punti di interazione degli slot del letto, relativi a bed_rect.topleft
# Assumiamo che l'NPC si avvicini ai piedi del letto.
# Devi adattare questi offset alla grafica del tuo letto e a come vuoi che gli NPC vi accedano.
# (X, Y)
BED_SLOT_1_INTERACTION_OFFSET = (-6, 97) 
BED_SLOT_2_INTERACTION_OFFSET = (26, 97)

# Offset per la posizione effettiva dell'NPC quando è NEL letto (per lo sprite del sonno)
# Relativi a bed_rect.topleft
BED_SLOT_1_SLEEP_POS_OFFSET = (TILE_SIZE * 0.5, TILE_SIZE * 0.8) 
BED_SLOT_2_SLEEP_POS_OFFSET = (TILE_SIZE * 1.5, TILE_SIZE * 0.8) 

TOILET_RECT_PARAMS = {"x": 800, "y": 100, "w": TILE_SIZE * 1, "h": TILE_SIZE * 2} 
TOILET_COLOR = (210, 210, 225) 

FOOD_POS = (100, 100) 
FOOD_RADIUS = min(10, TILE_SIZE // 2 - 2)
FOOD_COLOR = GREEN 
FOOD_VALUE = 30
FOOD_RESPAWN_TIME = 20.0 

# --- Action Values & Durations ---
SOCIAL_RECOVERY_RATE_PER_HOUR_PHONE = 40.0 
ENERGY_RECOVERY_RATE_PER_HOUR = 15.0
BLADDER_RELIEF_AMOUNT = 85      
TOILET_USE_DURATION_HOURS = 0.20 
FUN_GAINED_AMOUNT = 40 
HYGIENE_GAINED_AMOUNT = 70 

ROMANTIC_INTERACTION_CHANCE = 0.60       
INTIMACY_SATISFACTION_ROMANTIC = 60    
INTIMACY_SATISFACTION_AFFECTIONATE = 15  
SOCIAL_SATISFACTION_AFFECTIONATE = 10  
INTIMACY_INTERACTION_DURATION_HOURS = 1.0 
HEART_COLOR_ROMANTIC = RED                
HEART_COLOR_AFFECTIONATE = (255,105,180)  
PREGNANCY_CHANCE_FEMALE = 0.25
PREGNANCY_TERM_GAME_DAYS = DAYS_PER_MONTH 

# --- Need Bar Gradient Colors ---
NEED_BAR_BORDER_COLOR = (150, 150, 150) 

# --- UI Constants ---
UI_FONT_SIZE = 26 

# --- NPC AI Constants ---
NPC_SPEED = 80
NPC_MOVEMENT_SPEED_MULTIPLIERS = {
    0: 0.0, 1: 0.75, 2: 1.0, 3: 1.5, 4: 2.0, 5: 2.5   
}
NPC_HUNGER_THRESHOLD = 70
NPC_ENERGY_THRESHOLD = 30
NPC_SOCIAL_THRESHOLD = 40
NPC_BLADDER_THRESHOLD = 75 
NPC_FUN_THRESHOLD = 30     
NPC_HYGIENE_THRESHOLD = 25 
NPC_INTIMACY_THRESHOLD = 75 

NPC_EAT_REACH_DISTANCE = 15 
NPC_BED_REACH_DISTANCE = TILE_SIZE * 1.8 # Aumentato un po' per maggiore flessibilità con oggetti grandi
NPC_PARTNER_INTERACTION_DISTANCE = TILE_SIZE * 1.5 
NPC_TOILET_REACH_DISTANCE = TILE_SIZE * 1.0 
NPC_FUN_OBJECT_REACH_DISTANCE = TILE_SIZE * 1.0 
NPC_SHOWER_REACH_DISTANCE = TILE_SIZE * 1.0  

NPC_IDLE_WANDER_CHANCE = 0.02
NPC_WANDER_MIN_DIST_TILES = 3
NPC_WANDER_MAX_DIST_TILES = 8

# --- Need System Base Rates & Initial Values ---
DEFAULT_MAX_NEED_VALUE = 100.0
HUNGER_MAX_VALUE = DEFAULT_MAX_NEED_VALUE
HUNGER_INITIAL_MIN_PCT = 0.0  
HUNGER_INITIAL_MAX_PCT = 0.6  
HUNGER_BASE_RATE = 2.0        
HUNGER_HIGH_IS_GOOD = False   
HUNGER_RATE_MULTIPLIERS = {"Notte": 0.5, "Mattino": 1.2, "Mezzogiorno": 1.5, "Sera": 1.3}
ENERGY_MAX_VALUE = DEFAULT_MAX_NEED_VALUE
ENERGY_INITIAL_MIN_PCT = 0.4 
ENERGY_INITIAL_MAX_PCT = 1.0 
ENERGY_BASE_DECAY_RATE = 5.5 
ENERGY_HIGH_IS_GOOD = True
ENERGY_DECAY_MULTIPLIERS = {"Notte": 0.3, "Mattino": 1.0, "Mezzogiorno": 1.2, "Sera": 0.8}
SOCIAL_MAX_VALUE = DEFAULT_MAX_NEED_VALUE
SOCIAL_INITIAL_MIN_PCT = 0.4
SOCIAL_INITIAL_MAX_PCT = 1.0
SOCIAL_BASE_DECAY_RATE = 1.4
SOCIAL_HIGH_IS_GOOD = True
SOCIAL_DECAY_MULTIPLIERS = {"Notte": 0.7, "Mattino": 1.0, "Mezzogiorno": 1.2, "Sera": 1.5}
BLADDER_MAX_VALUE = DEFAULT_MAX_NEED_VALUE
BLADDER_INITIAL_MIN_PCT = 0.0
BLADDER_INITIAL_MAX_PCT = 0.65
BLADDER_BASE_FILL_RATE = 3.0 
BLADDER_HIGH_IS_GOOD = False
BLADDER_FILL_MULTIPLIERS = {"Notte": 0.4, "Mattino": 1.0, "Mezzogiorno": 1.2, "Sera": 1.0}
FUN_MAX_VALUE = DEFAULT_MAX_NEED_VALUE
FUN_INITIAL_MIN_PCT = 0.3
FUN_INITIAL_MAX_PCT = 1.0
FUN_BASE_DECAY_RATE = 2.5
FUN_HIGH_IS_GOOD = True
FUN_DECAY_MULTIPLIERS = {"Notte": 0.6, "Mattino": 1.0, "Mezzogiorno": 1.3, "Sera": 1.1}
HYGIENE_MAX_VALUE = DEFAULT_MAX_NEED_VALUE
HYGIENE_INITIAL_MIN_PCT = 0.5
HYGIENE_INITIAL_MAX_PCT = 1.0
HYGIENE_BASE_DECAY_RATE = 1.8
HYGIENE_HIGH_IS_GOOD = True
HYGIENE_DECAY_MULTIPLIERS = {"Notte": 0.5, "Mattino": 1.0, "Mezzogiorno": 1.2, "Sera": 1.0}
INTIMACY_MAX_VALUE = DEFAULT_MAX_NEED_VALUE 
INTIMACY_INITIAL_MIN_PCT = 0.0
INTIMACY_INITIAL_MAX_PCT = 0.3
INTIMACY_BASE_INCREASE_RATE = 0.8 
INTIMACY_HIGH_IS_GOOD = False 
INTIMACY_INCREASE_RATE_MULTIPLIERS = {"Notte": 1.0, "Mattino": 1.0, "Mezzogiorno": 1.1, "Sera": 1.3}

# --- Sprite Settings (used by Character class) ---
SPRITE_FRAME_WIDTH = 64  
SPRITE_FRAME_HEIGHT = 64 
SPRITE_WALK_ANIM_FRAMES = 4 
SPRITE_IDLE_ANIM_FRAMES = 1 
DEFAULT_ANIMATION_SPEED = 0.15  

SLEEP_SPRITESHEET_MALE_FILENAME = "malewhitesleep.png"
SLEEP_SPRITESHEET_FEMALE_FILENAME = "femalewhitesleep.png"
SLEEP_SPRITE_FRAME_WIDTH = 64  
SLEEP_SPRITE_FRAME_HEIGHT = 64 
# NUM_SLEEP_ANIM_FRAMES: Controllare e impostare in base agli spritesheet del sonno effettivi.
# Se ogni animazione di sonno (lato dx, supino, lato sx) ha N frame per un'animazione sottile.
NUM_SLEEP_ANIM_FRAMES = 2 # VERIFICARE QUESTO VALORE!
ANIM_ROW_SLEEP_SIDE_RIGHT = 0 
ANIM_ROW_SLEEP_ON_BACK = 1    
ANIM_ROW_SLEEP_SIDE_LEFT = 2  # Terza riga (commento pulito)

ANIM_ROW_WALK_UP = 8
ANIM_ROW_WALK_LEFT = 9
ANIM_ROW_WALK_DOWN = 10
ANIM_ROW_WALK_RIGHT = 11
ANIM_ROW_IDLE_UP = 22
ANIM_ROW_IDLE_LEFT = 23
ANIM_ROW_IDLE_DOWN = 24
ANIM_ROW_IDLE_RIGHT = 25

BUNDLE_FRAME_WIDTH = 64 
BUNDLE_FRAME_HEIGHT = 64 
BUNDLE_ANIM_ROW = 4
BUNDLE_ANIM_FRAMES = 3